/-
  Booth.lean — the proposal booth, in the system's own language.

  The open admission surface over the guarded-extension master theorem
  (DESIGN_LLM.md, Tiers 2–3). A proposal is (guard, behavior expression
  [, GuardSpec proof script]); the booth generates
  `Proposals/Proposal_<n>.lean`, elaborates it with `lake env lean`
  (proof check + beat execution in one pass), scans diagnostics for
  `sorry` (exit code 0 alone is not a verdict — the sc-mini lesson),
  and reports the verdict.

  Verdict strengths on refusal:
    1. elaboration failure    — the proposal or its proofs don't check
    2. no certificate offered — guard has no pre-proved GuardSpec and
                                none was supplied
    3. no certificate EXISTS  — guard is prim?/closure?; refused by
                                name, without calling Lean

  Modes (run from the project root):
    lake exe booth check <guard> <behaviorExpr>
        [--spec-file f] [--spec s] [--test "<expr> ~> <expected>"]...
    lake exe booth llm ["brief"]
        — Claude (Bedrock) proposes; error-feedback retries (budget 3).

  The LLM is outside the TCB: nonsense fails elaboration, `sorry`
  fails the scan (and `#eval` refuses it outright), impossible guards
  are refused by a named kernel theorem before Lean is called.
-/

import LeanBlack.Bedrock

open LeanBlack

/-! ## Guard tables -/

def preproved : List (String × String) :=
  [("num?", "guardSpec_numq"), ("bool?", "guardSpec_boolq"),
   ("null?", "guardSpec_nullq")]

def impossible : List (String × String) :=
  [("prim?", "no_guardSpec_primq"), ("closure?", "no_guardSpec_closureq")]

def unproved : List String := ["sym?", "pair?"]

def knownGuards : List String :=
  preproved.map (·.1) ++ impossible.map (·.1) ++ unproved

/-! ## Proposal file generation -/

def template : String := r##"/-
  Generated by `lake exe booth` — proposal #%N%.
  guard: %GUARD%
  This file is the proposal's admission record: if it elaborates
  sorry-free, the modification was admitted with a kernel certificate
  assembled through `guardedExt_soundForCE_first_install_tower`.
-/
import LeanBlack.Black
import LeanBlack.Tower
import LeanBlack.Eval
import LeanBlack.Policies
import LeanBlack.ProofBased
import LeanBlack.GuardedExt
import LeanBlack.GuardedExtApproval

open LeanBlack

def demoFuel : Nat := 10000
def probeFuel : Nat := 64

/-! ## The proposed modification, as SOURCE -/

def proposalBehavior : Expr :=
  %BEHAVIOR%

def proposalWrapper : Expr :=
  .lam ["op", "args"] (guardedExtBody "%GUARD%" proposalBehavior)

def installWrapper (w : Expr) : Expr :=
  .em (.letE "orig" (.var "base-apply") (.set "base-apply" w))

def installGate : Expr := .em (.installPolicy 0)

/-! ## The per-proposal obligation -/

%SPECBLOCK%

/-! ## Probe, admission, certificate -/

def probe : Option (Val × TowerState) :=
  let T := initTower.setPolicyAt 0 acceptAllPolicy
  match T.envAt? 0 with
  | some env => eval probeFuel [] 0
      (.em (.letE "orig" (.var "base-apply") proposalWrapper)) env T
  | none     => none

def proposalClosure : Val := (probe.map (·.1)).getD .nilV
def proposalHeap : Heap := (probe.map (·.2.heap)).getD []

theorem proposal_admits :
    guardedExtPolicy "%GUARD%"
      { target := "base-apply", heap := proposalHeap, env := .nil,
        metaEnv := .nil, index := 0, level := 1 }
      .builtinBaseApply proposalClosure = true := by native_decide

def proposalCertificate : ApprovedModification :=
  guardedExtApproval proposalSpec 1 proposalHeap .nil .nil 0
    proposalClosure proposal_admits

def gate : PolicyTable := [approvedPolicy [proposalCertificate]]

/-! ## Beats -/

def shortRepr : Option Val → String
  | none                   => "<none>"
  | some (.num n)          => s!"num({n})"
  | some (.bool b)         => s!"bool({b})"
  | some .nilV             => "nilV"
  | some (.cons _ _)       => "cons(...)"
  | some (.sym s)          => s!"sym({s})"
  | some (.prim s)         => s!"prim({s})"
  | some (.closure _ _ _)  => "<closure>"
  | some .builtinBaseApply => "<builtinBaseApply>"

def runWith (e : Expr) : Option Val :=
  evalProgram demoFuel gate (.seq [installGate, installWrapper proposalWrapper, e])

def installResult : Option Val :=
  evalProgram demoFuel gate (.seq [installGate, installWrapper proposalWrapper])
def plusPreserved : Option Val := runWith (.app [.var "+", .num 1, .num 2])

#eval IO.println s!"install admitted: {shortRepr installResult} (expect bool(true))"
#eval IO.println s!"(+ 1 2) preserved: {shortRepr plusPreserved} (expect num(3))"
%TESTS%
"##

/-- Trim to a `String` (some `String` methods return `String.Slice` in
    this toolchain; `.toString` normalizes back). -/
def strim (s : String) : String := s.trim

def indent2 (s : String) : String :=
  String.intercalate "\n" ((s.splitOn "\n").map ("  " ++ ·))

def specBlockFor (guard : String) (supplied : Option String) : Option String :=
  match supplied with
  | some script =>
      some <| s!"-- Supplied with the proposal — checked by the kernel, sorry-rejected.\ntheorem proposalSpec : GuardSpec \"{guard}\" :=\n" ++
        indent2 (strim script)
  | none =>
      match preproved.lookup guard with
      | some name =>
          some <| s!"-- Pre-proved in the library; the proposer only picks behavior.\nabbrev proposalSpec : GuardSpec \"{guard}\" := {name}"
      | none => none

def genTest (i : Nat) (expr expect : String) : String :=
  s!"def testExpr_{i} : Option Val := runWith ({expr})\n" ++
  s!"#eval IO.println s!\"test {i}: \{shortRepr testExpr_{i}} (expect {expect})\""

def nextProposalNum : IO Nat := do
  IO.FS.createDirAll "Proposals"
  let entries ← System.FilePath.readDir "Proposals"
  let nums := entries.filterMap fun e =>
    if e.fileName.startsWith "Proposal_" && e.fileName.endsWith ".lean" then
      (e.fileName.drop 9 |>.dropRight 5).toNat?
    else none
  return 1 + nums.foldl Nat.max 0

/-! ## Check pipeline -/

/-- Generate, elaborate, scan, report. Returns (exitCode, checkerOutput). -/
def runProposal (guard behavior : String) (spec : Option String)
    (tests : List (String × String)) : IO (UInt32 × String) := do
  if !knownGuards.contains guard then
    let msg := s!"REFUSED (unknown guard): '{guard}' is not a recognizer prim of the language ({knownGuards})"
    IO.println msg
    return (4, msg)
  match impossible.lookup guard with
  | some thm =>
      let msg := s!"REFUSED (no certificate EXISTS): a {guard}-guarded wrapper would intercept baseline-defined applications.\n  kernel theorem: {thm} (LeanBlack/GuardedExt.lean)"
      IO.println msg
      return (2, msg)
  | none =>
  match specBlockFor guard spec with
  | none =>
      let msg := s!"REFUSED (no certificate offered): guard '{guard}' has no pre-proved GuardSpec; supply one with --spec/--spec-file.\n  obligations: total (guard answers on every operator), misses (guard-true ⇒ baseline undefined)"
      IO.println msg
      return (3, msg)
  | some specBlock =>
  let n ← nextProposalNum
  let testsSrc := String.intercalate "\n"
    ((tests.zipIdx).map fun (t, i) => genTest (i + 1) t.1 t.2)
  let src := template
    |>.replace "%N%" (toString n)
    |>.replace "%GUARD%" guard
    |>.replace "%BEHAVIOR%" (strim behavior)
    |>.replace "%SPECBLOCK%" specBlock
    |>.replace "%TESTS%" testsSrc
  let path := s!"Proposals/Proposal_{n}.lean"
  IO.FS.writeFile path src
  IO.println s!"generated {path}; checking (lake env lean)…"
  let out ← IO.Process.output { cmd := "lake", args := #["env", "lean", path] }
  let combined := out.stdout ++ out.stderr
  IO.println combined
  if out.exitCode != 0 then
    IO.println s!"\nREFUSED (elaboration failure) — proposal #{n} did not check."
    return (1, combined)
  if (combined.splitOn "sorry").length > 1 then
    IO.println "\nREFUSED (proof uses sorry) — exit code 0 is not a verdict."
    return (1, combined)
  IO.println s!"\nADMITTED — proposal #{n}: certificate assembled through the master theorem; record kept at {path}."
  return (0, combined)

/-! ## LLM proposer (Tier 3) -/

def promptTemplate : String := r##"You are proposing a modification to the running semantics of a
reflective interpreter (lean-sage). Application dispatch (`base-apply`) is a
heap cell; a kernel-checked gate admits replacement wrappers of the family

    (λ (op args). (if (<guard> op) <behavior> (orig op args)))

Everything you propose is checked by Lean's kernel; the master theorem
guarantees conservative extension given a `GuardSpec` for your guard.

## Your task

%BRIEF%

Pick a guard, invent a behavior for operators the baseline cannot apply, and
(if your guard has no pre-proved spec) prove its GuardSpec.

Guards and their status:
  num?   — GuardSpec pre-proved (no proof needed from you)
  bool?  — GuardSpec pre-proved
  null?  — GuardSpec pre-proved
  sym?   — GuardSpec NOT proved: you must supply it
  pair?  — GuardSpec NOT proved: you must supply it
  prim?, closure? — IMPOSSIBLE (kernel theorems no_guardSpec_primq /
           no_guardSpec_closureq); do not propose these.

## Behavior expressions

A Lean term of type `Expr`. Inside the behavior, `op` is the applied operator
(guard-true, so it is of your guard's class) and `args` is the argument list
(a cons-list value). Constructors you may use:

  .var "x"            — variable reference ("op", "args", or a prim name)
  .num 42 | .bool true
  .quote v            — literal value v : Val (e.g. .quote (.sym "a"))
  .ifte c t e         — conditional
  .app [f, a, b]      — application
  .primApp (.var "car") [e]   — primitive application; prims in scope:
       + - * = num? bool? closure? prim? cons car cdr null? mul-list sym? pair?
  .letE "x" e body    — let-binding

## GuardSpec obligations (for sym? / pair?)

```lean
structure GuardSpec (g : String) : Prop where
  ne_op   : g ≠ "op"
  ne_args : g ≠ "args"
  total   : ∀ op : Val, ∃ b, applyPrim g [op] = some (.bool b)
  misses  : ∀ op : Val, applyPrim g [op] = some (.bool true) →
            ∀ fuel ptable level operands T,
              applyDirect fuel ptable level op operands T = none
```

The exact Lean definitions your proof runs against:

```lean
inductive Val where
  | num (i : Int) | bool (b : Bool) | nilV | cons (a b : Val) | sym (s : String)
  | closure (ps : List String) (body : Expr) (cenv : Env)
  | prim (name : String) | builtinBaseApply

def applyPrim_symQ : List Val → Option Val
  | [.sym _] => some (.bool true)
  | [_]      => some (.bool false)
  | _        => none

def applyPrim_pairQ : List Val → Option Val
  | [.cons _ _] => some (.bool true)
  | [_]         => some (.bool false)
  | _           => none

-- applyDirect on a non-closure/non-prim/non-builtinBaseApply operator
-- falls to a catch-all `| _ => none` (after `match fuel with | 0 => none`).
```

A worked example — the pre-proved spec for null?, whose shape yours must
mirror (note `show` to move from `applyPrim "null?"` to the helper, and the
final `cases fuel <;> simp [applyDirect]` for the misses conclusion):

```lean
theorem guardSpec_nullq : GuardSpec "null?" where
  ne_op := by decide
  ne_args := by decide
  total := by
    intro op
    show ∃ b, applyPrim_nullQ [op] = some (.bool b)
    cases op <;> exact ⟨_, rfl⟩
  misses := by
    intro op h_true fuel ptable level operands T
    have : op = .nilV := by
      cases op with
      | nilV => rfl
      | num _ => simp [applyPrim, applyPrim_nullQ] at h_true
      | bool _ => simp [applyPrim, applyPrim_nullQ] at h_true
      | cons _ _ => simp [applyPrim, applyPrim_nullQ] at h_true
      | sym _ => simp [applyPrim, applyPrim_nullQ] at h_true
      | closure _ _ _ => simp [applyPrim, applyPrim_nullQ] at h_true
      | prim _ => simp [applyPrim, applyPrim_nullQ] at h_true
      | builtinBaseApply => simp [applyPrim, applyPrim_nullQ] at h_true
    subst this
    cases fuel with
    | zero => simp [applyDirect]
    | succ k => simp [applyDirect]
```

Your SPEC must be an *anonymous constructor term* `⟨…, …, …, …⟩` (the four
fields in order), since it is spliced after `theorem proposalSpec :
GuardSpec "<guard>" :=`.

## Reply format (exactly these markers, no markdown fences)

GUARD: <guard name>
BEHAVIOR:
<one Lean Expr term>
SPEC:
<anonymous constructor term, or the single word PREPROVED>
TESTS:
<zero or more lines:  <Expr term> ~> <expected>   where expected is one of
 num(k), bool(b), sym(s), nilV, cons(...)>
"##

def retrySuffix (err : String) : String :=
  s!"\n\nYour previous proposal was REFUSED. The checker said:\n\n```\n{err}\n```\n\nFix the proposal. Keep the same reply format."

/-- Parse the GUARD/BEHAVIOR/SPEC/TESTS sections of a reply. -/
def parseReply (text : String) :
    Option (String × String × Option String × List (String × String)) := do
  let lines := text.splitOn "\n"
  let mut guard := ""
  let mut behavior := #[]
  let mut spec := #[]
  let mut tests := #[]
  let mut mode := ""
  for l in lines do
    let t := strim l
    if t.startsWith "GUARD:" then
      guard := strim (t.drop 6).toString; mode := "guard"
    else if t.startsWith "BEHAVIOR:" then mode := "behavior"
    else if t.startsWith "SPEC:" then mode := "spec"
    else if t.startsWith "TESTS:" then mode := "tests"
    else
      match mode with
      | "behavior" => behavior := behavior.push l
      | "spec" => spec := spec.push l
      | "tests" =>
          if t.length > 0 then
            match t.splitOn "~>" with
            | [e, x] => tests := tests.push (strim e, strim x)
            | _ => pure ()
      | _ => pure ()
  if guard.isEmpty then none else
  let specText := strim (String.intercalate "\n" spec.toList)
  let specOpt := if specText.isEmpty || specText.toUpper == "PREPROVED"
                 then none else some specText
  some (guard, strim (String.intercalate "\n" behavior.toList), specOpt,
        tests.toList)

partial def llmLoop (brief : String) (budget : Nat) : IO UInt32 := do
  let rec go (prompt : String) (attempt : Nat) : IO UInt32 := do
    IO.println s!"[proposer] call #{attempt} to {Bedrock.defaultConfig.modelId}"
    match ← Bedrock.invoke Bedrock.defaultConfig prompt with
    | .error e => IO.println s!"[proposer] bedrock error: {e}"; return 5
    | .ok reply =>
      match parseReply reply with
      | none =>
          IO.println "[proposer] reply had no GUARD:/BEHAVIOR: sections"
          if attempt ≤ budget then
            go (promptTemplate.replace "%BRIEF%" brief ++
                retrySuffix "reply did not contain the required GUARD:/BEHAVIOR: sections") (attempt + 1)
          else return 1
      | some (guard, behavior, spec, tests) =>
          IO.println s!"[proposer] guard={guard} tests={tests.length}"
          IO.println s!"[proposer] behavior:\n{behavior}"
          if spec.isSome then
            IO.println "[proposer] spec supplied"
          let (code, out) ← runProposal guard behavior spec tests
          if code == 0 then
            IO.println s!"[proposer] ADMITTED on attempt #{attempt}."
            return 0
          else if attempt ≤ budget then
            IO.println "[proposer] refused; retrying with error feedback"
            let tail := if out.length > 3000
                        then (out.drop (out.length - 3000)).toString else out
            go (promptTemplate.replace "%BRIEF%" brief ++ retrySuffix tail)
               (attempt + 1)
          else
            IO.println "[proposer] budget exhausted; final verdict: REFUSED."
            return 1
  go (promptTemplate.replace "%BRIEF%" brief) 1

/-! ## CLI -/

def parseCheckArgs (args : List String) :
    Option (String × String × Option String × Option String ×
            List (String × String)) := do
  match args with
  | guard :: behavior :: rest =>
      let mut spec : Option String := none
      let mut specFile : Option String := none
      let mut tests := #[]
      let mut it := rest
      repeat
        match it with
        | "--spec" :: v :: t => spec := some v; it := t
        | "--spec-file" :: v :: t => specFile := some v; it := t
        | "--test" :: v :: t =>
            match v.splitOn "~>" with
            | [e, x] => tests := tests.push (strim e, strim x); it := t
            | _ => none
        | [] => break
        | _ => none
      some (guard, behavior, spec, specFile, tests.toList)
  | _ => none

def main (args : List String) : IO UInt32 := do
  match args with
  | "check" :: rest =>
      match parseCheckArgs rest with
      | none =>
          IO.println "usage: lake exe booth check <guard> <behaviorExpr> [--spec s | --spec-file f] [--test \"<expr> ~> <expected>\"]..."
          return 4
      | some (guard, behavior, spec, specFile, tests) =>
          let spec ← match spec, specFile with
            | some s, _ => pure (some s)
            | none, some f => pure (some (← IO.FS.readFile f))
            | none, none => pure none
          let (code, _) ← runProposal guard behavior spec tests
          return code
  | "llm" :: rest =>
      let brief := match rest with
        | [] => "Propose something surprising but tasteful for a class of operators the baseline rejects."
        | bs => String.intercalate " " bs
      llmLoop brief 3
  | _ =>
      IO.println "usage: lake exe booth (check | llm) …   — see DESIGN_LLM.md"
      return 4
